Check if Xcode is installed

diff --git a/build b/build
--- a/build
+++ b/build
@@ -10,6 +10,14 @@ entry_points=
 combined_objs=
 ldflags=
 
+xcode_path=$(xcode-select -p 2> /dev/null)
+
+if [ ! $? -eq 0 ] || [ -z "$xcode_path" ] || [ "$xcode_path" = /Library/Developer/CommandLineTools ]
+then
+	printf "Error: Xcode is not installed.\n" 1>&2
+	exit 1
+fi
+
 rm -f *.o gen/progs.h gen/*_main.c log/*.txt "$exec"
 
 if [ "$1" = clean ]
