Prefix Add prefix to error message and redirect to stderr

diff --git a/build b/build
--- a/build
+++ b/build
@@ -40,7 +40,7 @@ do
 	linkfilelist=$(echo $project_path/build/$project.build/Release/$prog.build/Objects-normal/x86_64/*.LinkFileList)
 
 	if [ ! -e "$linkfilelist" ]; then
-		printf 'xcodebuild failed (exit: %d)\n' "$exit"
+		printf 'Error: xcodebuild failed (exit: %d)\n' "$exit" 1>&2
 		exit 1
 	fi
 
